### ISSUE TITLE
[FEATURE] Eve App 4.2 Issue with homebridge-website-to-camera

### ISSUE THREAD

**Issue by palasinio** [werthdavid/homebridge-website-to-camera#17]
@werthdavid 
The lates Eve for HomeKit App v4.2 is causing issues with several Homebridge Plugins.
They changed something so that the serial number of a device is linked somehow in the background. This was not with previous Eve versions.
Problems causing now like described here.
homebridge/homebridge#2503
So all devices/switches from homebridge-website-to-camera can't be sorted anymore and can't get an icon for each device separately.

Do you see a solution to fix this "Eve" Issue, by changing something in your plugin?

Thanks again for your work and the time you are investing generally.

**Comment by werthdavid** [comment]
Thanks for the explanation. I will look into it. Haven’t done anything regarding Eve for quite a while now..

**Comment by werthdavid** [comment]
Please try homebridge-website-to-camera@1.5.0 and let me know if that helps

**Comment by palasinio** [comment]
@werthdavid: Big THX for maintaining.
Right now I upgraded to HB 1.0.3 and the latest version of your plugin. For EVE to rediscover it is nescessary to remove the app.
Inbetween EVE restored previous behaviour /w version 4.2.1 and I was not able test /w 4.2.

But after updates I had to readd the "cams" and while doing that this happens:
```
[2020-4-28 23:48:04] [website-camera] identify
[2020-4-28 23:48:05] TypeError: callback is not a function
    at CameraAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-website-to-camera/CameraAccessory.js:25:13)
    at CameraAccessory.emit (events.js:310:20)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:85:12)
    at Accessory.emit (events.js:310:20)
    at Accessory.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Accessory._this._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:259:12)
    at Identify.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:248:16)
    at Identify.emit (events.js:310:20)
    at Identify.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Identify.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)
[2020-4-28 23:48:05] Got SIGTERM, shutting down Homebridge...
```
No problem, HB restarts and everything is okay, but this always will happen when pressing the "ID" button in EVE or Home app.

**Comment by werthdavid** [comment]
Sorry, I don't have a homebridge instance running at the moment so I can't test it...
Can you please try with homebridge-website-to-camera@1.5.1

**Comment by palasinio** [comment]
Sorry, that didn‘t help, but I had to add the cams again. No need to hurry. This error could be reproduced by clicking the identify button.

**Comment by werthdavid** [comment]
Ok I've setup my bridge again, homebridge-website-to-camera@1.5.2 should be working, sorry for the inconvenience. I'm not sure though, if the Eve problem is resolved with that as well

**Comment by palasinio** [comment]
@werthdavid Great - everything seems to be okay now. THX! (and so fast)
