### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by mgiacomo72** [werthdavid/homebridge-website-to-camera#26]
Hi, I installed you plugin but after configuration an error in homebridge status page is shown:

[9/15/2020, 7:47:24 PM] [website-camera] Starting new instance of Chromium: /usr/bin/chromium-browser
[9/15/2020, 7:47:24 PM] [website-camera] Error: Failed to launch the browser process!
cannot read mount namespace identifier of pid 1: Permission denied

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/Launcher.js:615:20)
    at Interface.<anonymous> (/usr/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/Launcher.js:605:56)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

I use Ubuntu Linux distribution and "Lubuntu" interface, this is my config in homebridge:

       {
            "platform": "website-camera",
            "cameras": [
                {
                    "name": "Test",
                    "url": "https://github.com",
                    "height": 400,
                    "width": 400,
                    "chromiumPath": "/usr/bin/chromium-browser"
                }
            ]
        }

can you heal me to understand how solve the situation?

Thanks in advance

Best regards
Giacomo

**Comment by mgiacomo72** [comment]
To complete my issue, chromium-browser opens correctly from the command line terminal in the desktop environment.

**Comment by werthdavid** [comment]
Are you running homebridge with a different user?

**Comment by mgiacomo72** [comment]
Hi David,

I use an ubuntu distribution with LXQT as my desktop environment.
The desktop LQT environment LXQT automatically login in with user “homebridge”.

From the desktop environment opening a terminal window, the program "/usr/bin/chromium-browser” opens correctly.

Opening the Homebridge terminal from the web interface, I have the same user “homebridge”, you can see the attached image:

![Schermata 2020-11-18 alle 12 55 46](https://user-images.githubusercontent.com/71350373/99527653-6ec5e780-299d-11eb-897b-4e9a6543b312.png)

So I think that everything is running with the same user…
Do you have any idea what else i can check?

Thanks in advance

Best regards
Giacomo

**Comment by WattageGuy** [comment]
Any solution? Same problem.

**Comment by werthdavid** [comment]
@WattageGuy do you have the same error with "permission denied"?
