### ISSUE TITLE
Feature Request: puppeteer.launch parameter

### ISSUE THREAD

**Issue by palasinio** [werthdavid/homebridge-website-to-camera#29]
Hi @werthdavid:
Is it possible to you, to add arguments for puppeteer.launch in Screenshothelper.js?
1st: Add a config option (per webcam) to use "ignoreHTTPSErrors: true" i.e. for local websites with self signed certificates
2nd: use "--no-sandbox" only if current user is "root"

![grafik](https://user-images.githubusercontent.com/31258581/112538288-0013f300-8db0-11eb-8f0c-4cb68fd60990.png)

**Comment by werthdavid** [comment]
That should be no problem. I'll see when I can find some time

**Comment by werthdavid** [comment]
Please try it with homebridge-website-to-camera@1.6.0

**Comment by palasinio** [comment]
Perfect! HTTPS flag works as expected. Thank you very much!
Just missing in GUI settings. I cannot see I f Chromium is in sandbox mode - but guess this is working, too.
Maybe you like to implement an error picture if ssl error is thrown or website not found / reachable?

**Comment by werthdavid** [comment]
I'll look into that when I find time but I'll close this for now

**Comment by UnbendableStraw** [comment]
How do I use this? I've tried adding it to my config but I still get ssl protocol errors, I'm probably doing something wrong?

```json
{
    "platform": "website-camera",
    "cameras": [
        {
            "name": "HomeBridge Status",
            "ignoreHTTPSErrors": "true",
            "url": "https://192.168.1.102:8581/"
        }
    ]
}
```
```
[4/22/2021, 8:08:38 AM] [website-camera] Error: net::ERR_SSL_PROTOCOL_ERROR at https://192.168.1.102:8581/
    at navigate (/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at FrameManager.navigateFrame (/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at Frame.goto (/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at Page.goto (/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:784:16)
    at ScreenshotHelper.getScreenshot (/homebridge/node_modules/homebridge-website-to-camera/ScreenshotHelper.js:37:5)
```

Thank you!
