### ISSUE TITLE
ReferenceError: Categories is not defined

### ISSUE THREAD

**Issue by esp32x** [werthdavid/homebridge-website-to-camera#39]
ReferenceError: Categories is not defined
    at new CameraAccessory (/usr/local/lib/node_modules/homebridge-website-to-camera/CameraAccessory.js:38:31)
    at /usr/local/lib/node_modules/homebridge-website-to-camera/index.js:27:67
    at Array.map (<anonymous>)
    at Platform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-website-to-camera/index.js:27:55)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

**version**
homebridge-website-to-camera@2.0.2

**config**
```{
            "platform": "website-camera",
            "cameras": [
                {
                    "name": "Wikipedia",
                    "url": "https://de.wikipedia.org/wiki/Wikipedia:Hauptseite",
                    "timeout": 10000,
                    "renderTimeout": 1,
                    "cacheTime": 30000,
                    "chromiumPath": "/usr/bin/chromium-browser",
                    "live": "false",
                    "liveSnapshotInterval": 10000,
                    "liveRefreshInterval": 60000,
                    "livePort": 8554
                }
            ]
        },
```

**Comment by werthdavid** [comment]
Ooops. Seems like I forgot something there... can you test with v2.0.3 please?

**Comment by esp32x** [comment]
Looks better/good.
But now when I set "live" to "true", I get an infinite boot loop.
