### ISSUE TITLE
Infinite boot loop

### ISSUE THREAD

**Issue by esp32x** [werthdavid/homebridge-website-to-camera#40]
When I set "live" to "true", I get an infinite boot loop. 

```
[06/12/2021, 12:38:08] TimeoutError: Navigation timeout of 10000 ms exceeded
    at /usr/local/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
[06/12/2021, 12:38:08] Got SIGTERM, shutting down Homebridge...
...
[06/12/2021, 12:38:13] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[06/12/2021, 12:38:18] [HB Supervisor] Restarting Homebridge...
```

**config**
```
{
    "name": "Time",
    "url": "https://time.is/",
    "timeout": 10000,
    "renderTimeout": 100,
    "cacheTime": 5000,
    "chromiumPath": "/usr/bin/chromium-browser",
    "jsFile": "/home/pi/js/cookie_consent.js",
    "live": "true",
    "liveSnapshotInterval": 1000,
    "livePort": 8554
}
```

**Comment by werthdavid** [comment]
It works on my machine 😂  That's weird.. Have you tried any other website? Does the cookie_consent.js file change anything?

**Comment by esp32x** [comment]
Unfortunately, I can't get it to run with any website/configuration.

**config**
```
{
    "platform": "website-camera",
    "cameras": [
        {
            "name": "Wikipedia",
            "url": "https://de.wikipedia.org/wiki/Wikipedia:Hauptseite",
            "timeout": 3000,
            "renderTimeout": 100,
            "cacheTime": 9000,
            "chromiumPath": "/usr/bin/chromium-browser",
            "live": "true",
            "liveSnapshotInterval": 1000,
            "liveRefreshInterval": 30000,
            "livePort": 8554
        }
    ]
},
```


```
[06/12/2021, 14:06:29] [website-camera] Chromium started
[06/12/2021, 14:06:29] [website-camera] Opening new page
[06/12/2021, 14:06:31] [website-camera] Setting Viewport to 1920x1080
[06/12/2021, 14:06:31] [website-camera] Going to page: https://de.wikipedia.org/wiki/Wikipedia:Hauptseite
[06/12/2021, 14:06:34] TimeoutError: Navigation timeout of 3000 ms exceeded
    at /usr/local/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
[06/12/2021, 14:06:34] Got SIGTERM, shutting down Homebridge...
[06/12/2021, 14:06:39] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[06/12/2021, 14:06:44] [HB Supervisor] Restarting Homebridge...
[06/12/2021, 14:06:44] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[06/12/2021, 14:06:44] [HB Supervisor] Started Homebridge v1.3.8 with PID: 1074
[06/12/2021, 14:06:48] Loaded config.json with 1 accessories and 5 platforms.
[06/12/2021, 14:06:48] Loaded 11 cached accessories from cachedAccessories.
[06/12/2021, 14:06:48] ---
[06/12/2021, 14:06:52] Loaded plugin: homebridge-config-ui-x@4.41.3
[06/12/2021, 14:06:52] Registering platform 'homebridge-config-ui-x.config'
```

Can you post a configuration with reasonable and tested values where it works on your machine?

**Comment by werthdavid** [comment]
I did test with the configuration you provided. Did it work with version 1 of the plugin? Are you running homebridge inside docker? also HTTPS could be a problem, have you tested a HTTP-only website? What version of chromium do you have?

**Comment by esp32x** [comment]
- Raspberry Pi 3 Model B+
- Official Homebridge Raspberry Pi Image based on Raspbian Lite
- Linux homebridge 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
- Chromium 92.0.4515.98 Built on Raspbian , running on Raspbian 11
- Node.js Version v16.13.0
- Npm Version v8.1.3
- no Docker

**Comment by werthdavid** [comment]
What happens if you set "timeout" to 0 (disabled, might be good for heavy websites)?

**Comment by esp32x** [comment]
Setting "timeout" to 0 does not seem to disable it. The default value is 10000.

```
[07/12/2021, 11:53:44] [website-camera] Starting new instance of Chromium: /usr/bin/chromium-browser
[07/12/2021, 11:53:46] [website-camera] Chromium started
[07/12/2021, 11:53:46] [website-camera] Opening new page
[07/12/2021, 11:53:47] [website-camera] Setting Viewport to 1920x1080
[07/12/2021, 11:53:47] [website-camera] Going to page: https://de.wikipedia.org/wiki/Wikipedia:Hauptseite
[Wikipedia A616] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[07/12/2021, 11:53:57] [website-camera] TimeoutError: Navigation timeout of 10000 ms exceeded
    at /usr/local/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
[07/12/2021, 11:54:07] [website-camera] Opening new page
[07/12/2021, 11:54:07] [website-camera] Setting Viewport to 1920x1080
[07/12/2021, 11:54:07] [website-camera] Going to page: https://de.wikipedia.org/wiki/Wikipedia:Hauptseite
[Wikipedia A616] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[07/12/2021, 11:54:17] [website-camera] Loading finished, waiting 100ms before taking screenshot
[07/12/2021, 11:54:18] [website-camera] Created screenshot
[07/12/2021, 11:54:18] [website-camera] Got screenshot
```

**Comment by werthdavid** [comment]
Dang it, that's right of course...
Can you try the Website "http://neverssl.com"

**Comment by esp32x** [comment]
Neverssl works, but when I set "live" to "true", "homebridge" or "website-camera" hangs and I can't see any messages in the status log anymore.

**Comment by werthdavid** [comment]
So as a recap:
- it works if live is set to "false" (no crash, screenshot visible)?
- it hangs if live is set to "true" (crash before camera is activated/"clicked")?

**Comment by werthdavid** [comment]
Please reopen if necessary
