### ISSUE TITLE
Chromium Path wrong, doesn't work on Mac

### ISSUE THREAD

**Issue by FirePanther** [werthdavid/homebridge-website-to-camera#46]
On Mac the /usr folder is secured, so I can't even create a softlink for  `/usr/bin/chromium-browser`
I installed chromium with homebrew (`brew install --cask chromium` → `/opt/homebrew/bin/chromium`)
But after installing, I still get the old path as an error message:

```
[5/3/2022, 2:54:57 AM] Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/opt/homebrew/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I would love to test the new Apple TV integration :D sadly changing my Homeserver from a Linux device to a Mac prevented from doing so

**Comment by werthdavid** [comment]
Ooops. Verified it on my Mac... Update incoming

**Comment by werthdavid** [comment]
hope it works with latest (2.0.4)
