### ISSUE TITLE
Plugin läuft nicht mehr

### ISSUE THREAD

**Issue by guitardoc** [werthdavid/homebridge-website-to-camera#53]
Hallo,

seit ein paar Tagen läuft das Plugin nicht mehr. Ich bekomme folgende Fehlermeldungen:

`[11/28/2024, 10:04:34 PM] [homebridge-website-to-camera] Starting child bridge...
[11/28/2024, 10:04:35 PM] [homebridge-website-to-camera] Launched child bridge with PID 267064
[11/28/2024, 10:04:35 PM] Registering platform 'homebridge-website-to-camera.website-camera'
[11/28/2024, 10:04:35 PM] [homebridge-website-to-camera] Loaded homebridge-website-to-camera v2.0.5 child bridge successfully
[11/28/2024, 10:04:35 PM] Loaded 0 cached accessories from cachedAccessories.0E5A9250CB2E.
[11/28/2024, 10:04:35 PM] [homebridge-website-to-camera] Initialized ScreenshotHelper
[11/28/2024, 10:04:35 PM] Homebridge v1.8.5 (HAP v0.12.3) (homebridge-website-to-camera) is running on port 39846.
[11/28/2024, 10:04:35 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[11/28/2024, 10:04:35 PM] Touareg E782 is running on port 37971.
[11/28/2024, 10:04:35 PM] Please add [Touareg E782] manually in Home app. Setup Code: 674-87-138
[11/28/2024, 10:05:16 PM] [homebridge-website-to-camera] Starting new instance of Chromium: /usr/bin/chromium
[11/28/2024, 10:05:16 PM] [homebridge-website-to-camera] Chromium started
[11/28/2024, 10:05:16 PM] [homebridge-website-to-camera] Opening new page
[Touareg E782] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[Touareg E782] The image snapshot handler for the given accessory didn't respond at all! See https://homebridge.io/w/JtMGR for more info.
[11/28/2024, 10:05:43 PM] [homebridge-website-to-camera] Opening new page
[Touareg E782] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[Touareg E782] The image snapshot handler for the given accessory didn't respond at all! See https://homebridge.io/w/JtMGR for more info.
[11/28/2024, 10:06:31 PM] [homebridge-website-to-camera] Opening new page
[Touareg E782] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[Touareg E782] The image snapshot handler for the given accessory didn't respond at all! See https://homebridge.io/w/JtMGR for more info.
[11/28/2024, 10:07:06 PM] [homebridge-homeconnect] Found 1 appliance (0 added, 0 removed)
[11/28/2024, 10:07:29 PM] [homebridge-website-to-camera] Opening new page
[Touareg E782] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[Touareg E782] The image snapshot handler for the given accessory didn't respond at all! See https://homebridge.io/w/JtMGR for more info.
[11/28/2024, 10:08:12 PM] [homebridge-website-to-camera] Opening new page
[11/28/2024, 10:08:16 PM] [homebridge-website-to-camera] ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at Callback.<instance_members_initializer> (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:114:12)
    at new Callback (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:119:3)
    at CallbackRegistry.create (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:27:22)
    at Connection._rawSend (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Connection.ts:125:22)
    at CdpCDPSession.send (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/CDPSession.ts:95:29)
    at NetworkManager.addClient (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:110:14)
    at FrameManager.initialize (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/FrameManager.ts:208:30)
    at CdpPage.#initialize (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Page.ts:349:28)
    at Function._create (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Page.ts:105:27)
    at /var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Target.ts:258:24
[Touareg E782] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[Touareg E782] The image snapshot handler for the given accessory didn't respond at all! See https://homebridge.io/w/JtMGR for more info.
[11/28/2024, 10:08:44 PM] [homebridge-website-to-camera] ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at Callback.<instance_members_initializer> (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:114:12)
    at new Callback (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:119:3)
    at CallbackRegistry.create (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:27:22)
    at Connection._rawSend (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Connection.ts:125:22)
    at CdpCDPSession.send (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/CDPSession.ts:95:29)
    at NetworkManager.addClient (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:110:14)
    at FrameManager.initialize (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/FrameManager.ts:208:30)
    at CdpPage.#initialize (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Page.ts:349:28)
    at Function._create (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Page.ts:105:27)
    at /var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Target.ts:258:24`

Kann dies hier das Problem sein:

`[11/28/2024, 10:04:35 PM] Please add [Touareg E782] manually in Home app. Setup Code: 674-87-138`

Ich kann da aber nichts in Home hinzufügen. Wenn ich den Setup Code eingebe passiert nichts. 

Da ich nichts (wissentlich) verändert habe, bin ich etwas ratlos, warum das Plugin nicht mehr funktioniert...

**Comment by werthdavid** [comment]
Hmmm was für ne Webseite rufst du denn auf? Hat sich auf dieser was geändert? Da steht etwas von Timeout... Kommst du mit deinem PC auf die Website?

**Comment by guitardoc** [comment]
Die Webseite zeigt den Standort des Fahrzeugs an. Sie liegt bei mir auf dem Server (192.168.188.124:8082/vis/index.html?StandortFahrzeug#StandortFahrzeug) und wenn ich die URL in den Browser eingebe, dann wird die Seite auch richtig angezeigt.
Ich habe das Plugin gerade noch mal deinstalliert und neu installiert. Die Fehlermeldungen sind danach immer noch gleich...

Edit: Ich habe auch mal eine andere Webseite eingetragen welche nicht auf meinem Server liegt (die Webseite einer großen deutsche Zeitung... :-)), da ist das Problem das gleiche.

**Comment by guitardoc** [comment]
Konntest du hier möglicherweise schon was entdecken?

**Comment by guitardoc** [comment]
Hallo David, Ich wollte noch mal nachfragen, ob du schon Zeit hattest, dir das mal anzuschauen? Hier noch mal die Fehlermeldungen:

`[2/4/2025, 2:12:29 PM] [homebridge-website-to-camera] Opening new page
[Touareg E782] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[2/4/2025, 2:12:38 PM] [homebridge-website-to-camera] ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at Callback.<instance_members_initializer> (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:114:12)
    at new Callback (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:119:3)
    at CallbackRegistry.create (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:27:22)
    at Connection._rawSend (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Connection.ts:125:22)
    at CdpCDPSession.send (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/CDPSession.ts:95:29)
    at NetworkManager.addClient (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:110:14)
    at FrameManager.initialize (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/FrameManager.ts:208:30)
    at CdpPage.#initialize (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Page.ts:349:28)
    at Function._create (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Page.ts:105:27)
    at /var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Target.ts:258:24`

**Comment by werthdavid** [comment]
Hey, sorry, ich komme gerade leider nicht dazu, hoffe dass ich in 2 Wochen mal wieder etwas Zeit habe

**Comment by guitardoc** [comment]
Hallo, hab gerade noch mal das System aktualisiert (bin aber noch auf node 20.11.0 wegen eines anderen Plugins) und es kommen immer noch diese Fehlermeldungen:

[3/22/2025, 10:06:43 AM] [homebridge-website-to-camera] Starting new instance of Chromium: /usr/bin/chromium
[3/22/2025, 10:06:43 AM] [homebridge-website-to-camera] Chromium started
[3/22/2025, 10:06:43 AM] [homebridge-website-to-camera] Opening new page
[3/22/2025, 10:06:43 AM] [homebridge-website-to-camera] Setting Viewport to 960x540
[3/22/2025, 10:06:43 AM] [homebridge-website-to-camera] Going to page: 192.168.188.124:8082/vis/index.html?StandortFahrzeug#StandortFahrzeug
[3/22/2025, 10:06:43 AM] [homebridge-website-to-camera] ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at Callback.<instance_members_initializer> (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:114:12)
    at new Callback (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:119:3)
    at CallbackRegistry.create (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:27:22)
    at Connection._rawSend (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Connection.ts:125:22)
    at CdpCDPSession.send (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/CDPSession.ts:95:29)
    at navigate (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Frame.ts:201:39)
    at CdpFrame.goto (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/cdp/Frame.ts:166:7)
    at CdpFrame.<anonymous> (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/util/decorators.ts:63:21)
    at CdpPage.goto (/var/lib/homebridge/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/src/api/Page.ts:1649:35)
    at ScreenshotHelper.getPage (/var/lib/homebridge/node_modules/homebridge-website-to-camera/ScreenshotHelper.js:46:16)

**Comment by werthdavid** [comment]
Kannst du mal in deiner Konfiguration aus "192.168.188.124:8082/vis/index.html?StandortFahrzeug#StandortFahrzeug" ein "http://192.168.188.124:8082/vis/index.html?StandortFahrzeug#StandortFahrzeug" machen?

**Comment by guitardoc** [comment]
HURRRRRAAAA!!!!!! Ja, das war das Problem! Jetzt läuft es wieder! Vielen vielen ganz lieben herzlichen Dank!!!!

**Comment by werthdavid** [comment]
Ok gut, da bin ich Froh 😂  Hätte man auch mal früher drauf kommen können aber damit hatte ich nicht gerechnet...

**Comment by guitardoc** [comment]
Seltsam ist ja, dass ich an der Zeile nie etwas bewusst geändert hab. Die muss schon immer ohne http:// drin gestanden haben und es hat jahrelang funktioniert… komisch.

**Comment by werthdavid** [comment]
Hab vermutlich irgend ein chrome Update wo sich etwas geändert hat.. naja Hauptsache es läuft wieder!
